// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  static const FirebaseOptions windows = FirebaseOptions (
    apiKey: "AIzaSyC7my9e-nbEDQRouPIA0WHoG6f8xBY5Dsw",
    authDomain: "juara-cpns.firebaseapp.com",
    projectId: "juara-cpns",
    storageBucket: "juara-cpns.firebasestorage.app",
    messagingSenderId: "359125944960",
    appId: "1:359125944960:web:7ec52372e30bb2b17ef465",
    measurementId: "G-STY39DXYJX"
  );

  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  static const FirebaseOptions web = FirebaseOptions (
    apiKey: "AIzaSyC7my9e-nbEDQRouPIA0WHoG6f8xBY5Dsw",
    authDomain: "juara-cpns.firebaseapp.com",
    projectId: "juara-cpns",
    storageBucket: "juara-cpns.firebasestorage.app",
    messagingSenderId: "359125944960",
    appId: "1:359125944960:web:0588e00e093159c87ef465",
    measurementId: "G-G7QY8NYGX1"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFH96lTRlHV1-i1vE4SLgYbEiOWfo8Zuo',
    appId: '1:359125944960:android:157008b207052a957ef465',
    messagingSenderId: '359125944960',
    projectId: 'juara-cpns',
    storageBucket: 'juara-cpns.firebasestorage.app',
  );


}